name: Python CI

on:
  push:
    branches: [ main ] # Adjust if your main branch is different (e.g., master)
  pull_request:
    branches: [ main ] # Adjust if your main branch is different

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff # For linting

    - name: Lint with ruff
      run: |
        ruff check . --output-format=github
        # The --output-format=github will show annotations directly in PRs

    - name: Run unit tests
      run: |
        python -m pip install pytest pytest-cov
        pytest --cov=src -vv
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
