name: Python CI

on:
  push:
    branches: [ main ] # Adjust if your main branch is different (e.g., master)
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches: [ main ] # Adjust if your main branch is different
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

# Ensure only a single workflow run per PR or branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
              - 'tests/**'
              - 'pyproject.toml'
              - 'requirements.txt'
              - '.github/workflows/**'

  build:
    needs: changes
    if: needs.changes.outputs.src == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Detect comment-only changes
      id: comment_check
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
      run: python scripts/only_comments_changed.py

    - name: Install dependencies
      if: steps.comment_check.outputs.only_comments != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff pre-commit # For linting and pre-commit

    - name: Run pre-commit
      if: steps.comment_check.outputs.only_comments != 'true'
      run: |
        pre-commit run --show-diff-on-failure --color=always

    - name: Lint with ruff
      if: steps.comment_check.outputs.only_comments != 'true'
      run: |
        ruff check . --output-format=github
        # The --output-format=github will show annotations directly in PRs

    - name: Run unit tests
      if: steps.comment_check.outputs.only_comments != 'true'
      run: |
        python -m pip install pytest pytest-cov
        pytest --cov=src --cov-config=.coveragerc -vv
        coverage xml

    - name: Upload coverage to Codecov
      if: steps.comment_check.outputs.only_comments != 'true'
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
