name: Python CI

on:
  push:
    branches: [ main ] # Adjust if your main branch is different (e.g., master)
  pull_request:
    branches: [ main ] # Adjust if your main branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4 # Using a recent version

    - name: Set up Python
      uses: actions/setup-python@v5 # Using a recent version
      with:
        python-version: '3.10' # Match project's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff # For linting

    - name: Lint with ruff
      run: |
        ruff check . --output-format=github
        # The --output-format=github will show annotations directly in PRs

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p "test_*.py"
